### ISSUE TITLE
Adicionar tempo para expirar uma vaga

### ISSUE THREAD

**Issue by ThiagoSilvaDevelop** [tasafo/tasafo_jobs#28]
Na listagem de vagas temos muitas vagas com datas antigas e que já foram preenchidas, porém da uma impressão que ainda está aberta. **A intenção é retirar essas vagas de visualização** e deixar apenas como histórico.

**Comment by luizsanches** [comment]
Resolvida com https://github.com/tasafo/tasafo_jobs/pull/32
